### PR TITLE
DotthzFile file loading after instantiation.

### PR DESCRIPTION
**Pull request by JasperWB**
Hi,

I've been playing around with loading .thz files. I think it may enhance functionality to allow the loading of files post instantiation, this would make processing and combining multiple .thz files a much simpler task. I've implemented this by moving the loading logic to a private _load method which is called by the load constructer as well as a new add_from_file method.

It may also be helpful to show the use of the constructors more explicitly in the example, as their use may not be obvious to newer python users, so I've edited the example to file to show this alongside the new loading functionality.

Take a look and let mw know what you think.

Best wishes,
Jasper

### CODE REVIEW

**Comment by hacknus** [comment]
Hello Jasper,

Thanks for your inputs! The issue with string stripping is definitely a good catch (#2 )!

About your other inputs: I think it may generally be a good idea to rethink the current structure. I'm not a fan of the `new` method, I think we should use an `__init__()` and think about implementing [context managers](https://book.pythontips.com/en/latest/context_managers.html) for the file, this way we would always provide the path in the beginning and it is consistent with how python users interface with other file types (for example csv, h5py, etc):

```python
import h5py
import numpy as np
with h5py.File("mytestfile.hdf5", "w") as f:
     dset = f.create_dataset("mydataset", (100,), dtype='i')
```

I think also both `DotthzMetaData` and `DotthzMeasurement` would benefit from an `__init__()` that already takes parameters.

Please, let me know what you think about that!

I'm not sure what we would gain from loading the files post instantiation and how this makes combining multiple .thz files simpler, can you explain that?

**Comment by JasperWB** [comment]
Hi Linus,

I generally agree with your assessment, given the complexity of the format an explicit init is probably the way to go. Re: context managers I also think this is a good idea, requiring a filepath makes sense given the purpose of the format. For the metadata and measurement classes its not clear to me what would go in their inits other than attribute assignments, in which case the dataclass decorator does that automatically if I'm not mistaken.

My thinking with loading files post instantiation was a.) an assumption that people may initialise with the default constructor not realising there are multiple constructors but still want to load a file,  b.) combining .thz files is something that's needed somewhat often in my group, c.) most potential users of this will only be familiar with Python for data analysis and scripting. For them the way to load and combine multiple files wouldn't necessarily be super obvious.

That being said on further thought I think that falls into category of quality of life functions, which is something to think about at a later date, and should really have any relation to how the object gets initialised. I am just very conscious that making this as simple as possible to use will help with adoption.

**Comment by hacknus** [comment]
> For the metadata and measurement classes its not clear to me what would go in their inits other than attribute assignments, in which case the dataclass decorator does that automatically if I'm not mistaken.
> 
Yes you are right, we only need it for the `DotTHzFile`!

> My thinking with loading files post instantiation was 
a.) an assumption that people may initialise with the default constructor not realising there are multiple constructors but still want to load a file, 

I think this is more of a documentation problem, if the code is well documented, then it should also be clear what constructors to use.

>b.) combining .thz files is something that's needed somewhat often in my group, 

I see! Out of curiosity, can you give me an example of how you combine `.thz` files?

>c.) most potential users of this will only be familiar with Python for data analysis and scripting. For them the way to load and combine multiple files wouldn't necessarily be super obvious.
> 
> That being said on further thought I think that falls into category of quality of life functions, which is something to think about at a later date, and should really have any relation to how the object gets initialised. I am just very conscious that making this as simple as possible to use will help with adoption.

Yes, I agree. I think I'll merge this PR, but I will work on a second branch to implement a context manager and make the handling of the `DotTHzFile` more similar to the `h5py` library, as it should serve as a light-weight wrapper around that library.

**Comment by JasperWB** [comment]
Currently CaTx is used to merge files, as it allows you to import multiple .thz files then re-export the measurements into a single file. It's a useful feature when, for whatever reason, you have to break up your measurements during a long experiment. Not super common, but comes up enough in my experience to be worth consideration.

**Comment by hacknus** [comment]
I thought some more about it and I have a new proposition. The object should be considered as a data-container, not as a file-representation. So it should probably be renamed to `DotthzData ` instead of `DotthzFile `.

A context manager does not really make sense, since the data-container should live longer than just the read/write process of the file.

Maybe something like this:

```python
class DotthzData:
    def __init__(self):
        self.groups = {}
        self.file = None

    @classmethod
    def from_data(cls, data: np.ndarray, meta_data: DotthzMetaData):
        measurement = DotthzMeasurement(datasets={"ds1": data}, meta_data=meta_data)
        return cls(groups={"Measurement 1": measurement})
```

and a similar method `from_file` for loading the file from a path?

@JasperWB What are your thoughts on this?

**Comment by JasperWB** [comment]
I'm not sure I agree, just thinking through its actually use the following core use-cases come to mind for me:

1. Writing a new file. Here having it as a persistent data-container would allow you add measurements dynamically rather than all at once, but I think this is of limited value compared to storing your measurements in another iterable then writing them all at once.
2. Reading data for plotting/processing. In this case there is no writing back to the file, so again I think it makes most sense to load the file, store the measurements in some other iterable. There's not any utility here to keeping it open.
3. Editing the metadata of an existing file. To me this is the most plausible case for a persistent object, but again I think the utility is limited. Doing this by iterating over measurements in a context manager makes the most sense to me.

From my perspective it makes the most sense for the `DotthzMeasurement` to be the persistent data-container, with users holding them in an iterable and reading/writing them in a context manager. DotthzFile really does then become just a wrapper around h5py. 

This seem the most intuitive workflow to me, but maybe there are use-cases I'm missing. I'm curious to get your input.

**Comment by hacknus** [comment]
Fair enough. I'm convinced, thanks for the fast response!

**Pull request merged**
